In [1]:
import math as m
import numpy as np

In [2]:
my_array = np.array([1,2,3,4,5])
print(my_array)

[1 2 3 4 5]


In [3]:
my_array2 = np.array([1,2,3,4,5,6])

print(my_array + my_array2)

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [5]:
print(my_array.shape)
print(my_array2.shape)

(5,)
(6,)


In [7]:
print(my_array2[5])
print(my_array2[2:5])

6
[3 4 5]


In [9]:
mi_lista = [[2,3,4], [5,7,9]]
my_array3 = np.array(mi_lista)
my_array3

array([[2, 3, 4],
       [5, 7, 9]])

In [11]:
print(my_array3.ndim) # cantidad de dimensiones de un array
print(my_array3.size) # cantidad de elementos de un array

2
6


In [13]:
mi_lista2 = [[2,3,4,4], [5,7,9,45], [8,10,-5,45]]
my_array3D = np.array(mi_lista2)
my_array3D.ndim

2

In [14]:
print(my_array3D.shape)

(3, 4)


In [15]:
mi_lista3 = [[[1,2], [2,4], [5,6]],[[7,8], [9,10], [11, 12]]]
my_array3 = np.array(mi_lista3)
my_array3.ndim

3

In [16]:
print(my_array3.shape)

(2, 3, 2)


In [17]:
mi_lista = [[2,3,4], [5,7,9]]
my_array3 = np.array(mi_lista)
my_array3

array([[2, 3, 4],
       [5, 7, 9]])

In [19]:
print(my_array3[0,2])
print(my_array3[:,1])

4
[3 7]


In [20]:
array_ceros = np.zeros(shape = (2,8))
array_ceros

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
array_ceros.ndim

2

In [23]:
#np.zeros?
array_ceros.shape

(2, 8)

In [25]:
array_ceros.size

16

In [26]:
def mi_funcion():
    '''
    Esta es la documentacion de mi funcion.....
    '''
    #esto es un comentario aparte
    return True
  

In [27]:
mi_funcion?

In [28]:
array_unos = np.ones(10)
array_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones?

In [30]:
print(np.random.randn(10, 2))

[[ 0.97427417 -0.19948361]
 [-0.29532273  1.37274006]
 [ 2.34799172 -0.13233254]
 [ 0.60095783  1.46331552]
 [-1.83885146 -0.41081616]
 [ 2.17419942 -1.39347185]
 [ 0.47712232 -1.12460321]
 [ 0.19975502  1.49163144]
 [-0.63512383 -0.44569671]
 [ 3.22050838 -0.21647333]]


In [33]:
r = np.random.randn(1000)
print(r.ndim)
print(r.shape)
print(r.mean())

1
(1000,)
0.022165210056601096


In [34]:
#Genera un array con enteros al azar
np.random.randint(5, 10, 4)

array([6, 7, 6, 7])

In [35]:
np.random.randint?

In [36]:
# arange(start, stop, step)
np.arange(2,16,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [37]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)
print(a)
print(b)
print(a==b)

[[-0.55424004  0.32072584  0.60636516]
 [-0.82466939 -0.465644    1.11994272]
 [ 0.45052468 -0.4114708  -0.35460739]]
[[ 0.48286134  0.51954853  0.61173373]
 [ 0.4545696   0.06018731  1.39287086]
 [-0.09615877  0.96730647  1.22988431]]
[[False False False]
 [False False False]
 [False False False]]


In [38]:
r

array([ 2.42977214e-01, -5.36515104e-01, -2.68241851e+00, -1.24988517e+00,
        6.97199282e-01, -1.54451607e+00,  1.15490508e-02, -4.58461563e-01,
        7.24509105e-01, -1.72405076e+00, -1.82770854e+00,  1.61689385e-01,
       -4.24133150e-01,  1.49608304e+00,  1.01794102e+00,  9.21727411e-01,
        1.06345857e-01,  2.42253245e-01,  9.85327873e-01,  1.46416042e+00,
       -4.12064855e-01,  1.36293041e+00,  1.29523901e+00,  1.54185512e-01,
        2.73573184e-01,  6.72485918e-01, -9.27376617e-02, -4.02451523e-01,
       -7.15444558e-01,  6.21662660e-01, -1.55052456e-01, -1.27329540e+00,
        1.11617774e+00,  1.01375997e+00,  5.08318222e-01, -8.07418108e-01,
       -2.13756873e-02,  7.53822960e-01,  1.07028506e-02,  9.00173431e-01,
       -1.44668104e+00, -4.42976587e-01, -1.02061333e+00,  1.61444102e+00,
        5.63630879e-01, -8.82059621e-02,  4.75562246e-01, -6.53990839e-01,
        9.84765726e-01,  8.24490886e-01,  1.14958920e-01,  1.47201544e-02,
        4.34920844e-01, -

In [39]:
print(r.mean())
print(np.var(r))
print(np.sum(r))
print(np.min(r))
print(np.max(r))

0.022165210056601096
1.0007826008639187
22.165210056601097
-4.16945151482648
2.7761594370960774


In [40]:
# Crear una matriz de 10x10 con 1's en los borders y 0 en el interior
# 1 1 1 1 1 1
# 1 0 0 0 0 1
# 1 0 0 0 0 1
# 1 1 1 1 1 1

array = np.zeros (shape = (10,10)) 
print(array)
print("-----------")
array[0,:] = 1
array[9,:] = 1
array[:,0] = 1
array[:,9] = 1
print(array)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
-----------
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
matriz10_10 = np.ones(shape = (10,10))
for i in range(1,9):
    for j in range(1,9):
        matriz10_10[i,j] = 0
        
matriz10_10


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
z = np.ones((10,10))
print(z)
print("-----------")
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
-----------
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
