In [1]:
import math as m
import numpy as np

In [2]:
print(np.pi)

3.141592653589793


In [3]:
np.pi == m.pi

True

In [4]:
my_array = np.array([10,11,12,13,14,15,16,17,18])
my_lista = [10,11,12,13,14,15,16,17,18]
print(type(my_array))
print(type(my_lista))

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
my_lista + my_lista

[10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [6]:
print(my_lista + 3)

TypeError: can only concatenate list (not "int") to list

In [7]:
mi_lista2 = [i + 3 for i in my_lista]
print(my_lista)
print(mi_lista2)

[10, 11, 12, 13, 14, 15, 16, 17, 18]
[13, 14, 15, 16, 17, 18, 19, 20, 21]


In [8]:
print(my_lista * 3)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 12, 13, 14, 15, 16, 17, 18]


In [9]:
mi_lista3 = [i * 3 for i in my_lista]
print(my_lista)
print(mi_lista3)

[10, 11, 12, 13, 14, 15, 16, 17, 18]
[30, 33, 36, 39, 42, 45, 48, 51, 54]


In [10]:
print(my_array)

[10 11 12 13 14 15 16 17 18]


In [11]:
array1 = np.array(mi_lista2)
array2 = np.array(mi_lista3)
print(mi_lista2)
print(mi_lista3)
print(array1 + array2)

[13, 14, 15, 16, 17, 18, 19, 20, 21]
[30, 33, 36, 39, 42, 45, 48, 51, 54]
[43 47 51 55 59 63 67 71 75]


In [12]:
array3 = array1 + array2
print(array3)
print(type(array3))

[43 47 51 55 59 63 67 71 75]
<class 'numpy.ndarray'>


In [18]:
lista1 = [1,2,3,4]
lista2 = [10,33,2,5]
#lista3 = [11,35,5,9]
lista3 = []
for i in range(len(lista1)):
    lista3.append(lista1[i] + lista2[i])
print(lista3)


[11, 35, 5, 9]


In [22]:
print(array1)
print(array2)
print("---------------")
print(array1 - array2)
print(array2 - array1)
print(array1 * array2)
print(array2 / array1)
print(array2 ** array1)
print(30**13)

[13 14 15 16 17 18 19 20 21]
[30 33 36 39 42 45 48 51 54]
---------------
[-17 -19 -21 -23 -25 -27 -29 -31 -33]
[17 19 21 23 25 27 29 31 33]
[ 390  462  540  624  714  810  912 1020 1134]
[2.30769231 2.35714286 2.4        2.4375     2.47058824 2.5
 2.52631579 2.55       2.57142857]
[ -765861888 -1555599935  1073741824 -1651651711 -1482031104  1307689001
           0   700739281   895483904]
15943230000000000000
